FROM python:3.10

ENV PYTHONUNBUFFERED=1

RUN mkdir /code

WORKDIR . /code/

RUN pip install -r requirements.txt

EXPOSE 8000

#  CMD["gunicorn","--chdir","blog","--bind", ":8000","blog.blog.wsgi.py:application"]

 CMD["python","manage.py","runserver","0.0.0.0:8000"]
